gText_Birch_Welcome::
	.string "Shiorin! Welcome fellow trainer\n"
	.string "to a neat scenario here:\l"
	.string "Touhoumon Timechaser's Ceremony\p"
	.string "My name is Shiori.\p"
	.string "But that's not really important\n"
	.string "for where you're going.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Puppet.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This Puppet I brough here as\n"
	.string "an example for what you'll be\l"
	.string "coming across in this little\l"
	.string "scenario here.\p"
	.string "You'll be assisting my fellow\n"
	.string "friends Kronii and Gigi with a\l"
	.string "ceremony they're preparing.\p"
	.string "They certainly need the assistance\n"
	.string "here, after all.\p"
	.string "But enough about the two here,\n"
	.string "what about you here?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you tomboyish?\n"
	.string "Or are you girly?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's in this\n"
	.string "this little scenario here.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Puppets where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I hope you have a good time\n"
	.string "in this scenario here.\p"
	.string "$"
